zenoss/ZenPacks.zenoss.Layer2

ZenPacks/zenoss/Layer2/edge_contraction.py
ZenPacks/zenoss/Layer2/network_tree.py
ZenPacks/zenoss/Layer2/tests/test_edge_contraction.py

To quote Joseph Hanson: "4. Do we need to show mac addresses (links) that don't go anywhere. If we could only show them when they link to another device it would go a long way towards reducing the clutter. "

Edge contraction and some nodes remove

---

ZenPacks/zenoss/Layer2/dsplugins.py

Fix VLAN community string. Ignore non-int VLANs.

---

README.mediawiki
ZenPacks/zenoss/Layer2/modeler/plugins/zenoss/snmp/CDPLLDPDiscover.py
ZenPacks/zenoss/Layer2/resources/js/views.js

Fix handling of IPv6 CDP neighbors.

---

README.mediawiki
ZenPacks/zenoss/Layer2/dsplugins.py

Avoid community@VLAN queries for non-Cisco devs.

---

README.mediawiki
ZenPacks/zenoss/Layer2/modeler/plugins/zenoss/snmp/ClientMACs.py
ZenPacks/zenoss/Layer2/patches.py

Fix modeling client MACs from labeled Cisco VLANs.

---

ZenPacks/zenoss/Layer2/patches.py

https://jira.zenoss.com/browse/ZEN-20860

ignore adding devices to catalog which could not be adapted

---

ZenPacks/zenoss/Layer2/configure.zcml
ZenPacks/zenoss/Layer2/impact.py

https://jira.zenoss.com/browse/ZEN-20285

new impact: switch impacts devices, nothing impacts switch

---

README.mediawiki

https://jira.zenoss.com/browse/ZEN-20725

Remove DynamicView documentation

---

ZenPacks/zenoss/Layer2/overrides.zcml
ZenPacks/zenoss/Layer2/patches.py

https://jira.zenoss.com/browse/ZEN-21264

fix ZEN-21264

---

ZenPacks/zenoss/Layer2/migrate/RemoveLayer2InfoTemplate.py

https://jira.zenoss.com/browse/ZEN-22309

remove monitoring template,fix ZEN-22309

---

ZenPacks/zenoss/Layer2/connections_provider.py

https://jira.zenoss.com/browse/ZEN-22887

ZEN-22887: Layer2 ZP breaks NetScalar data collection

---

ZenPacks/zenoss/Layer2/connections_catalog.py
ZenPacks/zenoss/Layer2/zenmapper.py

https://jira.zenoss.com/browse/ZEN-23124
Add possibility to override default Redis connection options.

ZEN-23124: Add Redis connction string configuration option

---

ZenPacks/zenoss/Layer2/connections_catalog.py

The main idea is to allow search for multiply keys per call. This reduces number of request to Redis and as result overall execution time.

ZEN-23212: Performance issue with getExpandedLinks() call

---

ZenPacks/zenoss/Layer2/connections_catalog.py

Fix for incorrect conflict resolving

ZEN-23212: Performance issue with getExpandedLinks() call (upd)

---

ZenPacks/zenoss/Layer2/network_tree.py

Switched all CatalogAPI requests to use batches. The same for ZEP requests.

ZEN-23212: Performance improvements for Network Map generating

---

ZenPacks/zenoss/Layer2/connections_provider.py

Reverts zenoss/ZenPacks.zenoss.Layer2#172

Revert "ZEN-23182: Layer2 ZenPack models internal interface MAC addresses of …"

---

ZenPacks/zenoss/Layer2/tests/test_edge_contraction.py

https://jira.zenoss.com/browse/ZEN-23805

ZEN-23805: Fix unit tests for edge_contraction

---

ZenPacks/zenoss/Layer2/migrate/AddRedisEndpoint.py
ZenPacks/zenoss/Layer2/migrate/RemoveConnectionsCatalog.py
ZenPacks/zenoss/Layer2/utils.py

https://jira.zenoss.com/browse/ZEN-23849

ZEN-23849: Fix upgrade from 1.1.1 to 1.2.1

---

ZenPacks/zenoss/Layer2/tests/test_connection_catalog.py
ZenPacks/zenoss/Layer2/tests/test_zenmapper.py

https://jira.zenoss.com/browse/ZEN-23851

ZEN-23851: Fix unit tests

---

README.mediawiki
ZenPacks/zenoss/Layer2/__init__.py
ZenPacks/zenoss/Layer2/modeler/plugins/zenoss/snmp/ClientMACs.py
ZenPacks/zenoss/Layer2/tests/test_modeler_plugins.py
ZenPacks/zenoss/Layer2/tests/test_utils.py
ZenPacks/zenoss/Layer2/utils.py

Fixes ZEN-23182
* Add zLocalMacAddresses
* Add utils is_valid_macaddr802 and filterMacSe
* Add and adjust unit tests

Add zLocalMacAddresses to remove MACs from mapping

---

README.mediawiki
ZenPacks/zenoss/Layer2/__init__.py
ZenPacks/zenoss/Layer2/patches.py

Fix NeighborSwitch errors after removing ZenPack

---

ZenPacks/zenoss/Layer2/network_tree.py

This is required because the Redis database backing the network map is not
consistent with ZODB. Specifically, devices and component entries in the
Redis database don't immediately get cleaned up when the devices and
components are deleted from ZODB.
The zenmapper service ultimately cleans these up on its next run, but we
have to work around stale entries regularly.
Fixes ZPS-88, ZPS-90.

Handle objects deleted from ZODB but not Redis

---

ZenPacks/zenoss/Layer2/network_tree.py

When we remove nodes from the graph because they've been deleted from
Zenoss, we sometimes end up creating nodes that are unreachable from the
root node. We shouldn't see this. So we'll just remove any nodes that
aren't reachable from the root.
Fixes ZPS-325.

network map: Remove nodes unreachable from root

---

README.html
README.mediawiki
ZenPacks/zenoss/Layer2/graph.py
ZenPacks/zenoss/Layer2/patches.py

See individual commits for details.
- Optimize modeling and zenmapper for devices with many connections. (68fa2c2)
- Eliminate Layer2 modeling overhead for vSphere devices. (682c79e)
Fixes ZPS-736.

Two isolated optimization changes

---

README.html
README.mediawiki
ZenPacks/zenoss/Layer2/suppression.py
ZenPacks/zenoss/Layer2/tests/test_suppression.py

Fix suppression when zL2PotentialRootCause is set

---

ZenPacks/zenoss/Layer2/resources/js/render_network_map.js

There was some confusion about how to handle hashes between the two
different scopes in with the network map is displayed: global and
device. I made the functions that needed to be aware of scope aware of
it, and made the synchronization of the sidebar settings and the URL
query string values more explicit.
Fixes ZPS-1287 & ZPS-2463.

Fix "Set the root device or component" flares

---

README.html

Scheduled to be fixed in CiscoUCS 2.6.3.
Refs ZPS-2465.

Document lack of UCS layer3 information

---

README.html
ZenPacks/zenoss/Layer2/NeighborSwitch.py
ZenPacks/zenoss/Layer2/links.py
ZenPacks/zenoss/Layer2/patches.py
ZenPacks/zenoss/Layer2/utils.py

Fix links to work in Zenoss Cloud

---

ZenPacks/zenoss/Layer2/network_tree.py

* https://jira.zenoss.com/browse/ZEN-30541

ZEN-30541: remove prefix for root_id on CZ

---

ZenPacks/zenoss/Layer2/graph.py
ZenPacks/zenoss/Layer2/tests/test_suppression.py
ZenPacks/zenoss/Layer2/tests/test_zenmapper.py
ZenPacks/zenoss/Layer2/zenmapper.py

- Added unique index to edges table.
- Fixed --(clear|optimize|device) zenmapper options.
- Delete in chunks of 1,000 to avoid over-locking and deadlocks.
Fixes ZPS-4402.

Additional optimizations related to ZPS-4402

---

ZenPacks/zenoss/Layer2/modeler/plugins/zenoss/snmp/ClientMACs.py
ZenPacks/zenoss/Layer2/tests/test_modeler_plugins.py

For SNMPv1 and SNMPv2c Cisco allows access to the fowarding tables by
using different community strings. For SNMPv3 they instead use separate
contexts.
https://community.cisco.com/t5/network-management/bridge-mib-with-snmp-v3/m-p/1179195#M48799

ZPS-6684: support BRIDGE-MIB by context for SNMPv3
