zenoss/ZenPacks.zenoss.Layer2

README.mediawiki, ZenPacks/zenoss/Layer2/modeler/plugins/zenoss/snmp/CDPLLDPDiscover.py
CDPLLDPDiscover is only instantiated once per zenmodeler process. The
way self.rm and self.hashes were being used was causing CDP and LLDP
neighbor results to be shared from one switch to the next if they were
modeled by the same zenmodeler process.
Fixes ZEN-17023.
=> Stop sharing neighbors between switches.

README.mediawiki, ZenPacks/zenoss/Layer2/dsplugins.py, ZenPacks/zenoss/Layer2/migrate/ReplaceLayer2InfoTemplate.py, ZenPacks/zenoss/Layer2/modeler/plugins/zenoss/snmp/ClientMACs.py, setup.py
This is being done to allow switching zenpython back to the epoll
reactor. Layer2 was the only ZenPack that had a PythonDataSourcePlugin
requiring the select reactor.
=> Replace Layer2Info with ClientMACs modeler.

ZenPacks/zenoss/Layer2/migrate/AddZenmapperService.py
Added migration to add `zenmapper` service on ZP upgrade. This one should be applied only on Zenoss 5.1.x and higher, as from 5.1.x services are not installed during ZP upgrade.
=> ZEN-23475: zenmapper daemon is not displayed

ZenPacks/zenoss/Layer2/zenmapper.py
This prevent multiple workers to get intersected chunks and loose keys in redis because part of devices don't fit in any of chunks.
=> Sorting list of devices before chunking it for workers.

ZenPacks/zenoss/Layer2/network_tree.py
Fix for:
```
Traceback (most recent call last):
File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Layer2-1.2.1dev95_e801241-py2.7.egg/ZenPacks/zenoss/Layer2/patches.py", line 177, in getJSONEdges
layers=layers, full_map=full_map
File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Layer2-1.2.1dev95_e801241-py2.7.egg/ZenPacks/zenoss/Layer2/network_tree.py", line 53, in get_connections_json
connections = get_connections(obj, depth, layers)
File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Layer2-1.2.1dev95_e801241-py2.7.egg/ZenPacks/zenoss/Layer2/network_tree.py", line 277, in get_connections
get_connections([rootnode], depth)
File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Layer2-1.2.1dev95_e801241-py2.7.egg/ZenPacks/zenoss/Layer2/network_tree.py", line 218, in get_connections
depth - 1)
File …
```
=> ZEN-23212: Performance improvements for Network Map generating (upd)

ZenPacks/zenoss/Layer2/edge_contraction.py, ZenPacks/zenoss/Layer2/network_tree.py, ZenPacks/zenoss/Layer2/resources/js/render_network_map.js
Limited number of nodes to 2000. On QA's host it takes about 20 sec to process, for 1000 nodes -- ~15 sec.
Traversing recursion was removed, as in such case it will process only first batches from root node and will go deeper. As result there may be a cases where only some part of children nodes are processed, as processing of their children (and their children, and their ....) will reach a nodes limit.
=> ZEN-23212: Limit number of nodes for network map

ZenPacks/zenoss/Layer2/connections_catalog.py
`CatalogAPI.get_connected()` method was converted to generator. So now traversing could be interrupted from caller. This is used during links generating as we show only first 100 linked devices.
=> ZEN-23212: Convert  to generator

ZenPacks/zenoss/Layer2/network_tree.py
In case when all nodes are visited, there was a possibility to request impacted and impactors for empty set, as result catalog search returned all nodes in catalog.
=> ZEN-23835: Flare message on Network map after 8 value

README.mediawiki, ZenPacks/zenoss/Layer2/connections_catalog.py, ZenPacks/zenoss/Layer2/tests/test_connection_catalog.py
Most usages of CatalogAPI would instantiate it every time, which would
mean that on Zenoss 4 the 2 minute redis timeout would have to occur
each time. This change will allow immediate discovery of the correct
redis URL in Zenoss 5 and 4.
=> Fix potential 2 minute modeling delay in Zenoss 4

ZenPacks/zenoss/Layer2/modeler/plugins/zenoss/snmp/ClientMACs.py, ZenPacks/zenoss/Layer2/tests/test_modeler_plugins.py
We've seen data that indicates some Q-BRIDGE agent implementations don't
return the dot1qTpFdbAddress column because it's part of the table's
index, and can therefore be parsed. This fix first checks for the
column's value, but parses the MAC address from the table's index if it
can't be found.
Fixes ZEN-25336.
=> Q-BRIDGE: Handle missing dot1qTpFdbAddress column

ZenPacks/zenoss/Layer2/network_tree.py
Commit c400aaa regressed the default behavior of the network map to show
no layers instead of all layers. This resulted in a "No data." error
showing on all Network Map pages until the "Apply" button was clicked.
Fixes ZEN-26271.
=> Restore default map behavior to show all layers

README.mediawiki, ZenPacks/zenoss/Layer2/__init__.py
At least for its first release event suppression will be an opt-in
configuration. Once the functionality is proven we can consider enabling
it by default.
Fixes ZEN-25862.
=> Disable L2 event suppression by default

README.mediawiki, ZenPacks/zenoss/Layer2/networkMap.pt, ZenPacks/zenoss/Layer2/resources/css/network_map.css, ZenPacks/zenoss/Layer2/resources/js/graph_renderer.js, ZenPacks/zenoss/Layer2/resources/js/render_network_map.js, ZenPacks/zenoss/Layer2/resources/js/views.js
Two other unrelated tweak commits.
- Capitalize "Network Map" throughout UI.
- Don't select VLAN and VXLAN layers by default
Fixes ZEN-26288.
=> Clarify case of resources with no map data

ZenPacks/zenoss/Layer2/connections_provider.py, ZenPacks/zenoss/Layer2/suppression.py, ZenPacks/zenoss/Layer2/tests/test_suppression.py
The root cause of ZEN-25848 was that were were caching the status of the
vSphere device (endpoint) based on critical ping events from some of its
hosts. This circumvented the vSphere device's custom connection
provider's get_status implementation which would have properly reported
the vSphere device as up. This root cause is now fixed by treating
critical ping events as non-ping events for purposes of suppression if
they have a component field. This will work well both for L2 root cause
suppression and non-ping event suppression.
There was another event component issue in the default device connection
provider's get_status implementation that could have theoretically
caused this same kind of bug to occur on non-vSphere devices that don't
have their own connection provider get_status …
=> Fix two event component handling bugs

ZenPacks/zenoss/Layer2/resources/js/render_network_map.js
network map: Remove "no additional info" flare
Nodes not having additional info is now (as of v1.3.0 & ZPS-1) common.
The "no additional info attached" flare message now only serves to
concern the user that something is wrong when nothing is wrong.
Fixes ZPS-193.
=> network map: Remove "no additional info" flare

ZenPacks/zenoss/Layer2/connections_provider.py
Fix POSKeyError on first model of device
I didn't think a ZenPack could cause a POSKeyError, but here's a
completely reproducible way to create them. If you call _p_invalidate()
on a new object where _p_jar is is still None instead of a
ConnectionManager, you will get a POSKeyError when the transaction
attempts to commit.
Fixes ZPS-321.
=> Fix POSKeyError on first model of device

ZenPacks/zenoss/Layer2/connections.py, ZenPacks/zenoss/Layer2/modeler/plugins/zenoss/snmp/ClientMACs.py, ZenPacks/zenoss/Layer2/utils.py
Normalize MAC addresses to uppercase
The connections.get_device_by_mac function used by the "Client MAC
Addresses" display for network interfaces would search Redis for
connections to MAC addresses using the exact (case sensitive) MAC
addresses modeled into the interface's clientmacs property. There was
no normalization of IpInterface.clientmacs case. So sometimes this
would fail to find a match.
This fix normalizes both the modeling and search sides to use uppercase.
The connections_provider side that stores things in Redis was already
normalizing to uppercase.
Fixes ZPS-168.
=> Normalize MAC addresses to uppercase

README.mediawiki, ZenPacks/zenoss/Layer2/network_tree.py, ZenPacks/zenoss/Layer2/resources/js/render_network_map.js
The problem in ZPS-322 was that I classified nodes along one shortest
path from endpoint nodes to endpoint nodes as being "useful". Any MAC
nodes that weren't useful were pruned. This resulted in way too many MAC
nodes getting pruned because there was often a much shorter L3 path.
This fix is two-fold.
1. Only consider layer2 nodes for the shortest path calculation.
2. Unfavorably weight MAC node without a path.
This results in the right amount of MAC address nodes being left, and it
results in MAC address nodes without a path being much more likely to be
pruned. This is good, because the whole point of the "Show MAC
addresses" option on the network map is to allow the user to click on
MAC addresses to navigate directly to their associated interface.
There are some other small unrelated …
=> Only consider L2 paths when pruning redundant MACs

ZenPacks/zenoss/Layer2/network_tree.py, ZenPacks/zenoss/Layer2/resources/js/graph_renderer.js
This bug was introduced by 09f83dd in my attempt to remove nodes
unreachable from the root node from the graph. I failed to account for
the the graph algorithm requiring the root node to be in the graph.
Fixes ZPS-358.
=> Fix traceback when root node isn't in the graph

ZenPacks/zenoss/Layer2/network_tree.py
The "remove_redundant_macs" function was running even when the user
selected "Show dangling connectors". Dangling connectors are redundant
by that functions definition, so they were being removed.
The fix is simply to not remove redundant MACs when "Show dangling
connectors" is selected.
Fixes ZPS-359.
=> Fix "Show dangling connectors" for MAC addresses

README.mediawiki, ZenPacks/zenoss/Layer2/patches.py
Switch to updating Layer2 information in
ModelerService.remote_applyDataMaps() instead of Device.setLastChange().
It turns out that for devices that submit many DataMaps while modeling
such as vSphere, the Device.setLastChange() method is called once for
every DataMap that results in a change. We only need to be called once
for the device if anything on it changed.
As an example, our large vcsim1 vCenter simulator results in over 24,000
DataMaps being applied for its initial model. This would result in the
Layer2 information in Redis being updated up to that many times when it
only had to happen once. So we're talking about a 24,000 times speedup
in that extreme case.
Fixes ZPS-736.
=> Fix modeling performance with many component types

ZenPacks/zenoss/Layer2/macs_catalog.py
Fixes [ZPS-1267](https://jira.zenoss.com/browse/ZPS-1267)
Old version of OpenvSwitch ZP used `CatalogAPI` which was removed in
recent version of Layer2 ZP. This fix adds dummy version of this
API to avoid import errors before OpenvSwitch ZP will be upgraded.
=> Add deprecated CatalogAPI for compatibility with old ZenPacks

ZenPacks/zenoss/Layer2/nx/simple_paths.py, ZenPacks/zenoss/Layer2/suppression.py
There was a bug in Suppressor.get_shortest_paths that could result in an
infinite loop. Fixing the bug by properly implementing the shortest path
algorithm that was in place resulted in the algorithm taking too far too
long to execute on large topologies to be feasible during event
processing.
Newer versions of the networkx library such as version 11 shipped with
Zenoss 5 have a shortest_simple_paths algorithm that's optimal for this
use case. However, this algorithm doesn't exist in the networkx 1.3
version shipped with Zenoss 4.2.5. So I've copied the BSD-licensed code
into this ZenPack for use when it isn't available in the installed
networkx library.
Using the new algorithm the functional tests all pass, and the manual
performance tests show no sign of a performance regression. If …
=> Fix infinite loop in event suppression logic

README.html, README.mediawiki, ZenPacks/zenoss/Layer2/links.py, ZenPacks/zenoss/Layer2/tests/create_fake_devices.py, ZenPacks/zenoss/Layer2/tests/test_links.py
Fixes ZPS-1683
return an empty list if no neighbors are found for a device.
Also add unit tests for links.
=> Fix an invalid expanded device link

README.html, README.mediawiki, ZenPacks/zenoss/Layer2/resources/js/views.js
Fixes ZPS-1663
Add client MACs to subinterface, mgmt interface dropdown lists.
=> Add client MACs to sub/mgmt iface dropdown

ZenPacks/zenoss/Layer2/graph.py, ZenPacks/zenoss/Layer2/tests/test_graph.py
Some queries were not finishing their transactions. This would leave the
metadata locked for l2_* tables. Removed explicit transactions from the
code entirely, and used MySQL's autocommit option.
Fixes the Zenoss 5 portion of ZPS-2466.
=> Fix issue with unfinished transactions

ZenPacks/zenoss/Layer2/graph.py
Zenoss 4 will typically have "zodb-host localhost" in global.conf. This
will cause Layer2 to attempt to connect to MySQL using the UNIX domain
socket in /tmp/mysql.sock instead of over the network. This results in
the following error.
Traceback (most recent call last):
...
File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Layer2-1.4.0.dev16+ge521d33-py2.7.egg/ZenPacks/zenoss/Layer2/graph.py", line 344, in connect
self.connection = MySQLdb.connect(**connect_kwargs)
File "/opt/zenoss/lib/python/MySQLdb/__init__.py", line 81, in Connect
return Connection(*args, **kwargs)
File "/opt/zenoss/lib/python/MySQLdb/connections.py", line 187, in __init__
super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)") …
=> Fix Zenoss 4 "/tmp/mysql.sock" errors

ZenPacks/zenoss/Layer2/graph.py
MySQLdb connection objects are not thread safe. Weird bugs were
occurring because one thread was picking up the results of another
thread's query.
Fixes ZPS-2463.
=> Fix thread-unsafe usage of MySQL connection

ZenPacks/zenoss/Layer2/tests/test_impact.py
Impact 5.2.2 introduced a ZCML job directive that requires that tests
load Products.ZenJobber's meta.zcml before running Impact tests.
Fixes ZPS-2485.
=> Fix unit test failure w/ Impact >= 5.2.2

ZenPacks/zenoss/Layer2/graph.py
It was found that the DISTINCT qualifier on these queries is unnecessary
because the merge_layers method is performing a distinct operation of
its own. Furthermore it was found that during large-scale parallel
modeling with Impact installed that the DISTINCT qualifier doubled the
CPU usage of mariadb-model due to creation of temporary tables.
Fixes ZPS-2550.
=> Remove DISTINCT to improve MySQL performance

README.html
Move installation-related notes from the "Troubleshooting" section to
the "Installation" section. These are things the user would want to be
aware of before installing, not once they've already encountered a
problem.
Fixes ZPS-2168.
=> Add "Installation" section to documentation

README.html, ZenPacks/zenoss/Layer2/__init__.py
This would only occur for collectors that had their configuration saved
after the Layer2 ZenPack was installed because l2_gateways would still
be in their _properties, but there'd be no default value for it because
the Layer2 ZenPack patches that default in.
Fixes ZPS-2581.
=> Fix "AttributeError: l2_gateways" after removal

README.html, ZenPacks/zenoss/Layer2/connections.py, ZenPacks/zenoss/Layer2/graph.py, ZenPacks/zenoss/Layer2/zenmapper.py
The primary culprit was broken change detection. Each cycle zenmapper
was only supposed to process nodes (devices) that had changed since
their l2_edges information was last written to the database. Due to the
underlying behavior of "INSERT IGNORE" that was being used, the last
change recorded in the l2_providers was never being updated. This means
that once a device changed a second time, it would have to be processed
on every subsequent cycle of zenmapper. That problem has been fixed.
Even with that, zenmapper will cause database fragmentation. So I also
added a periodic (daily) optimization of all of the l2_* tables.
Fixes ZPS-3548.
=> Fix ZODB growth caused by zenmapper

README.html, ZenPacks/zenoss/Layer2/configure.zcml, ZenPacks/zenoss/Layer2/resources/js/views.js
Recursively marshalling the info for a network interface can sometimes
result in the following traceback.
Traceback (most recent call last):
File "/opt/zenoss/Products/ZenUtils/extdirect/router.py", line 184, in _processDirectRequest
response.result = _targetfn(**data)
File "<string>", line 2, in getInfo
File "/opt/zenoss/Products/Zuul/decorators.py", line 128, in serviceConnectionError
f = func(*args, **kwargs)
File "/opt/zenoss/Products/Zuul/routers/device.py", line 309, in getInfo
data = Zuul.marshal(process, keys)
File "/opt/zenoss/Products/Zuul/__init__.py", line 105, in marshal
keys, marshallerName, objs)
File "/opt/zenoss/Products/Zuul/__init__.py", line 120, in marshal
marshalled_dict[k] = marshal(obj[k], keys, marshallerName, objs)
File "/opt/zenoss/Products/Zuul/__init__.py", …
=> Fix zProdStateThreshold on client MAC addresses

README.html, ZenPacks/zenoss/Layer2/__init__.py
The problem with the previous approach of adding the neighbor_switches
relationship to just ZenModel.Device was that it wouldn't get added to
subclasses of Device which had already been imported and had their own
_relations extended from Device's default.
This approach works regardless of ZenPack initialization order. Adding
to Device._relations will cause all subclasses imported after Layer2 to
inherit it, and adding to all known subclases of Device will cause all
subclasses imported before Layer2 to get it.
Fixes ZPS-4062.
=> Add neighbor_switches relationship in all cases

README.html, ZenPacks/zenoss/Layer2/connections.py, ZenPacks/zenoss/Layer2/graph.py, ZenPacks/zenoss/Layer2/tests/test_graph.py, ZenPacks/zenoss/Layer2/tests/test_suppression.py, ZenPacks/zenoss/Layer2/tests/test_zenmapper.py, ZenPacks/zenoss/Layer2/zenmapper.py
The previous MySQL usage used a strategy of tracking all edges by the
"provider" that created them. A provider is an IConnectionsProvider
adapter. Anytime a change was detected in a provider either during
modeling or by zenmapper, all of the previous edges from that provider
were deleted from the l2_edges table, and the new set of edges were
inserted. This resulted in a lot of fragmentation for two reasons. We
were deleting a lot of rows, and the rows contained variable-length
columns so the space vacated by the deleted rows couldn't be guaranteed
to be reusable by the new rows. The problem would be exacerbated if
MySQL's purge thread fell behind.
The new strategy in this commit keeps the provider concept intact, but
instead of deleting and replacing all of the provider's edges when any …
=> Optimize MySQL usage to avoid table fragmentation

README.html, ZenPacks/zenoss/Layer2/__init__.py, ZenPacks/zenoss/Layer2/patches.py, ZenPacks/zenoss/Layer2/tests/test_patches.py, ZenPacks/zenoss/Layer2/tests/test_zenmapper.py, ZenPacks/zenoss/Layer2/zenmapper.py
New configuration properties that allow users control over when the
connectivity information for devices will be updated.
Implements ZPS-4496.
=> Add zL2UpdateOnModel and zL2UpdateInBackground

ZenPacks/zenoss/Layer2/connections.py, ZenPacks/zenoss/Layer2/graph.py, ZenPacks/zenoss/Layer2/impact.py, ZenPacks/zenoss/Layer2/tests/test_graph.py
It was found that the Graph.get_edges() was dominating the CPU time
spent on getting impact relationships for thousands of simulated Cisco
network devices in our performance lab. The reason this problem was so
severe in the performance lab is that the thousands of simulated devices
all appear to be directly connected at layer2. So in this case, each of
the 4080 devices had 4079 neighbors.
While we may never see that many layer2 neighbors in the real world, it
was a good opportunity to see how get_edges could be optimized.
The main problem was that get_edges was doing a node-by-node graph
traversal that required a round-trip to MariaDB to get the neighbors of
each neighbor. This routine was changed to only require one database
round trip per "hop" away from the root node.
The next …
=> improve Graph.get_edges() performance

ZenPacks/zenoss/Layer2/connections.py, ZenPacks/zenoss/Layer2/suppression.py
See the fix for ZPS-5712 (dc86ab2) that describes the optimization that
was done for that case. This change takes advantage of that optimization
to Graph.networkx_graph() for event suppression purposes.
On one particularly problematic device at a customer site this took the
time to calculate root causes during event processing from 350 seconds
to less than 1 second.
It is Suppressor.root_causes() that is responsible for almost all of the
time spent in Layer2 event processing. The following profiles are from
before this change, and after this change.
Profile of Suppressor.root_causes() before this change.
6881125 function calls (6871655 primitive calls) in 350.132 seconds
Ordered by: cumulative time
List reduced from 612 to 50 due to restriction <50>
ncalls  tottime  percall  cumtime …
=> optimize event suppression with ZPS-5712 fix

ZenPacks/zenoss/Layer2/graph.py
Upon upgrading zenoss-py-deps from MySQL-python 1.2.3 to 1.2.5 (a.k.a.
MySQLdb), we started seeing the following errors in zenmapper.
Traceback (most recent call last):
File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Layer2-1.4.3-py2.7.egg/ZenPacks/zenoss/Layer2/zenmapper.py", line 220, in update_nodes
added = connections.update_node(node, force=self.options.force)
File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Layer2-1.4.3-py2.7.egg/ZenPacks/zenoss/Layer2/connections.py", line 44, in wrapper
return f(*args, **kwargs)
File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Layer2-1.4.3-py2.7.egg/ZenPacks/zenoss/Layer2/connections.py", line 133, in update_node
provider.load()
File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.Layer2-1.4.3-py2.7.egg/ZenPacks/zenoss/Layer2/graph.py", line 481, in load
self.uuid)
File …
=> ZPS-7117: fix for changes in MySQLdb 1.2.5

ZenPacks/zenoss/Layer2/graph.py
In zenoss 6.5.0 we started seeing the flare message in UI with the
following text:
AttributeError 'Cursor' object has no attribute '_rows'
The problem appears when a request to MySQL fails. When a request fails,
it handled by try-except in https://github.com/zenoss/ZenPacks.zenoss.Layer2/blob/hotfix/1.4.4/ZenPacks/zenoss/Layer2/graph.py#L731
After that in 'else' block cursor is closed. But when the cursor is closing,
it checks the _executed field in the cursor, if it's not empty then cursor
fetches all remaining data and deletes a connection. But in our case, when
a request fails, the _executed field is not empty (but it should be empty)
and the cursor tries to fetch remaining data (but there is no data because
request failed) and we get the AttributeError. This change adds additional …
=> ZPS-7119 Handle AttributeError exception when we close MySQL cursor
